### ISSUE TITLE
Add Social Media Icons 

### ISSUE THREAD

**Issue by therajaryan** [therajaryan/Pick-A-Book#1]
Add Social Media Icons on the bottom-left corner, under 'JOIN US'. Remove the Form given there and replace it with the icons of Facebook, Instagram, Twitter and LinkedIn. Put hover effect on the icons such that on hover, the names of the social media platforms are displayed.

**Comment by TheFirstMe** [comment]
Can I have this?

**Comment by therajaryan** [comment]
> Can I have this?

Sure, go ahead.

**Comment by TheFirstMe** [comment]
@therajaryan Just made a PR.
